### ISSUE TITLE
Docker-compose: Error: Invalid value: File does not exist: main.py

### ISSUE THREAD

**Issue by DanGarion** [ziadhorat/Plex-Spot#2]
Hello, two issues to report.

The docker-compose.yml does not match what is in the readme. This may be as expected just not normal from my experience with other app builds, usually the compose matches what is in the readme.

When using the compose in the Readme I get the following error when I start the container.

2024-09-06T20:43:12.050949760Z Usage: streamlit run [OPTIONS] TARGET [ARGS]...
2024-09-06T20:43:12.050979862Z Try 'streamlit run --help' for help.
2024-09-06T20:43:12.050989430Z 
2024-09-06T20:43:12.050999906Z Error: Invalid value: File does not exist: main.py

**Comment by ziadhorat** [comment]
Heya @DanGarion ,

1. Yes you are correct, I will find a way to consolidate/hide the `docker-compose.yml` being used to build. (The one in the repo) The only compose visible should be to use the built images.

2. Just to verify, your `docker-compose.yml` looks similar to below yeah?
```yaml
version: '3'
services:
  plex-spot:
    container_name: plex-spot
    ports:
      - "8501:8501"
    environment:
      - PLEX_API_TOKEN=xxx
      - PLEX_SERVER_URL=http://localhost:32400
      - DEBUG=False
    image: ziadhorat/plex-spot
```
- The error `File does not exist` makes me think it might have been the build compose that was run instead of the one to use the pre-built image.
- However, if that's not the case and it's still failing, would you mind enabling the DEBUG environment variable and confirming they are all set as expected (URL & Token)?
- If all of the above is fine, do you mind sharing your CPU model? I do also expect some architectures to struggle with this image.

Thank you for your time & patience sir
